print("Welcome to the tip calculator!\n")
a=float(input("What was the total bill?"))
b=int(input("How much tip would you like to give? 10, 12, or 15?"))
c=int(input("How many people to split the bill?"))
payment=((a/c)*((b+100)/100))
print("Each person should pay: $%.2f"%payment)